# Generated by Django 3.2.8 on 2021-10-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('origin', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='flights',
            field=models.ManyToManyField(to='main_app.Flights'),
        ),
    ]
