# Generated by Django 3.2.8 on 2021-10-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211022_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='origin',
            field=models.CharField(max_length=50),
        ),
    ]
