# Generated by Django 3.2.8 on 2021-10-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_flights_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Flights',
        ),
        migrations.AlterField(
            model_name='city',
            name='flights',
            field=models.ManyToManyField(to='main_app.Flight'),
        ),
    ]
